#!/bin/bash

RED='\e[31m'
GREEN='\e[32m'
RESET='\e[0m'
declare -i STEPS=0
declare -i counter=1
declare -a numbers
declare -i hit=0
declare -i miss=0

while :
do
  random_number=${RANDOM: -1}
  echo -n -e "Step: ${counter}\n"
  read -p "Please enter number from 0 to 9 (q - quit): " input
  case "${input}" in

    [0-9])
      if [[ "${random_number}" == "${input}" ]]
        then
          echo "Hit! My number: ${random_number}"
	  number_string="${GREEN}${random_number}${RESET}"
	  hit+=1
	else
	  echo "Miss! My number: ${random_number}"
	  number_string="${RED}${random_number}${RESET}"
	  miss+=1
      fi
      let total=$(( hit + miss ))
      let hit_percent=$(( hit*100/total ))
      let miss_percent=$(( 100-hit_percent ))
      numbers+=("${number_string}")
      echo "Hit: ${hit_percent}%" "Miss: ${miss_percent}"
      if (( ${#numbers[@]} > 10 ))
	then
	  echo -e "Numbers: ${numbers[@]: -10}"
	else
	  echo -e "Numbers: ${numbers[@]}"
      fi
      counter+=1
    ;;
    q)
      echo "Bye"
      echo "Exit..."
      exit 0
    ;;
    *)
      echo "Not valid input"
      echo "Please repeat"
    ;;
    esac
done
